services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432" # using 5434 to avoid conflict with default postgres port on local machine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6378:6379"

  blog:
    build: .
    container_name: blog
    # comment out to use only nginx and don't allow requests to blog container directly but to only use nginx
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  celery:
    build: .
    container_name: celery
    command: celery -A blog worker --loglevel=info
    depends_on:
      - blog
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A blog beat --loglevel=info
    depends_on:
      - blog
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - blog
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9201:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
  es_data: